import { lucia } from "$lib/server/auth";
import { sequence } from '@sveltejs/kit/hooks';
import { type Handle, redirect } from '@sveltejs/kit';
import { minify } from 'html-minifier';

const minifyHtml: Handle = async ({ event, resolve }) => {
  return resolve(event, {
    transformPageChunk: ({ html, done }) => {
      return minify(html, {
		caseSensitive: true,
		collapseBooleanAttributes: true,
		collapseInlineTagWhitespace: true,
		collapseWhitespace: true,
		conservativeCollapse: false,
		continueOnParseError: true,
		decodeEntities: true,
		html5: true,
		includeAutoGeneratedTags: true,
		keepClosingSlash: false,
		minifyCSS: true,
		minifyJS: true,
		minifyURLs: true,
		preserveLineBreaks: false,
		preventAttributesEscaping: false,
		processConditionalComments: true,
		removeAttributeQuotes: true,
		removeComments: true,
		removeEmptyAttributes: true,
		removeEmptyElements: true,
		removeOptionalTags: true,
		removeRedundantAttributes: true,
		removeScriptTypeAttributes: true,
		removeStyleLinkTypeAttributes: true,
		removeTagWhitespace: true,
		sortAttributes: true,
		sortClassName: true,
		trimCustomFragments: true,
		useShortDoctype: true,
	  
		/* NEW/EXTRA settings */
		customAttrAssign: [/\{[{%][^}]+[}%]\}/],      // enable collapsing custom templating attributes
		// customAttrSurround: [/\{\{[^}]+\}\}/],        // support templating expressions
		customEventAttributes: [/^on[a-z]{3,}$/],     // extreme: minify inline event‐handlers too
		quoteCharacter: '\'',                           // force single‐quote attributes where possible
		ignoreCustomComments: []                        // don't ignore any comments – we already removeComments=true
	  });
    }
  });
};

const luciaAuth: Handle = async ({ event, resolve }) => {
	const sessionId = event.cookies.get(lucia.sessionCookieName);
	if (!sessionId) {
		event.locals.user = null;
		event.locals.session = null;
	} else {
		const { session, user } = await lucia.validateSession(sessionId);
		if (session && session.fresh) {
			const sessionCookie = lucia.createSessionCookie(session.id);
			event.cookies.set(sessionCookie.name, sessionCookie.value, {
				path: "/",
				...sessionCookie.attributes
			});
		}
		if (!session) {
			const sessionCookie = lucia.createBlankSessionCookie();
			event.cookies.set(sessionCookie.name, sessionCookie.value, {
				path: "/",
				...sessionCookie.attributes
			});
		}
		event.locals.user = user;
		event.locals.session = session;
	}

	return resolve(event);
};

const authGuard: Handle = async ({ event, resolve }) => {
	const protectedPaths = ['/dash', '/logout', '/-users/r', '/-doa', '/-logout'];
	const isProtected = protectedPaths.some((p) => event.url.pathname.startsWith(p));
	
	if (!event.locals.session && isProtected) {
		const isFetch = event.request.headers.get('accept')?.includes('application/json') || 
		                event.request.headers.get('x-sveltekit-action') === 'true';

		if (isFetch) {
			return new Response(JSON.stringify({ success: false, error: 'Session expired' }), {
				status: 401,
				headers: { 'content-type': 'application/json' }
			});
		}

		return new Response(null, {
            status: 303,
            headers: { location: "/login" }
        });
	}

	return resolve(event);
};

export const handle: Handle = sequence(
	luciaAuth,
	authGuard,
	minifyHtml
);
